# Generated by Django 3.2.9 on 2024-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiskeluseura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehtava',
            name='hinta',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tehtava',
            name='nimi',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
