# Generated by Django 5.0.2 on 2024-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiskeluseura', '0002_auto_20240303_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehtava',
            name='hinta',
            field=models.IntegerField(default=0),
        ),
    ]
